const { addonBuilder } = require("stremio-addon-sdk");
const axios = require("axios");
const cheerio = require("cheerio");

const manifest = {
    "id": "community.sukebei.rd",
        "version": "1.0.0",
            "name": "Sukebei+RD",
                "description": "Search Sukebei Nyaa and stream via Real-Debrid",
                    "logo": "https://i.imgur.com/wEy7mFk.png", 
                        "resources": ["catalog", "stream"],
                            "types": ["other", "movie", "series"],
                                "catalogs": [
                                        {
                                                    "type": "other",
                                                                "id": "sukebei_search",
                                                                            "name": "Sukebei Search",
                                                                                        "extra": [{ "name": "search", "isRequired": true }]
                                                                                                }
                                                                                                    ]
                                                                                                    };

                                                                                                    const builder = new addonBuilder(manifest);
                                                                                                    const RD_API_KEY = process.env.RD_API_KEY;

                                                                                                    // --- HELPER FUNCTIONS ---

                                                                                                    // 1. Scrape Sukebei for Search Results
                                                                                                    async function searchSukebei(query) {
                                                                                                        try {
                                                                                                                const url = `https://sukebei.nyaa.si/?f=0&c=0_0&q=${encodeURIComponent(query)}&s=seeders&o=desc`;
                                                                                                                        const { data } = await axios.get(url);
                                                                                                                                const $ = cheerio.load(data);
                                                                                                                                        const metas = [];

                                                                                                                                                $('tr.default, tr.success, tr.danger').each((i, element) => {
                                                                                                                                                            const titleRow = $(element).find('td:nth-child(2) a').not('.comments');
                                                                                                                                                                        const title = titleRow.text().trim();
                                                                                                                                                                                    const viewUrl = titleRow.attr('href');
                                                                                                                                                                                                // Extract ID from view URL (e.g. /view/123456 -> 123456)
                                                                                                                                                                                                            const id = viewUrl ? viewUrl.split('/').pop() : null;
                                                                                                                                                                                                                        
                                                                                                                                                                                                                                    // Get size for poster/description context
                                                                                                                                                                                                                                                const size = $(element).find('td:nth-child(4)').text().trim();

                                                                                                                                                                                                                                                            if (title && id) {
                                                                                                                                                                                                                                                                            metas.push({
                                                                                                                                                                                                                                                                                                id: `sukebei:${id}`,
                                                                                                                                                                                                                                                                                                                    type: "other",
                                                                                                                                                                                                                                                                                                                                        name: title,
                                                                                                                                                                                                                                                                                                                                                            poster: "https://via.placeholder.com/150?text=Sukebei", // No posters on Sukebei
                                                                                                                                                                                                                                                                                                                                                                                description: `Size: ${size}`
                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                            return metas;
                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("Scrape Error:", e.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                return [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 2. Scrape Specific Page to get Magnet
                                                                                                                                                                                                                                                                                                                                                                                                                                                    async function getMagnetFromId(id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const url = `https://sukebei.nyaa.si/view/${id}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const { data } = await axios.get(url);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const $ = cheerio.load(data);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const magnet = $('a[href^="magnet:"]').attr('href');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return magnet;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 3. Check Real-Debrid Cache and Unrestrict
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                async function resolveRD(magnet) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Extract Hash
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const infoHash = magnet.match(/xt=urn:btih:([a-zA-Z0-9]+)/)[1].toLowerCase();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // A. Check Availability
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const availUrl = `https://api.real-debrid.com/rest/1.0/torrents/instantAvailability/${infoHash}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const availRes = await axios.get(availUrl, { headers: { Authorization: `Bearer ${RD_API_KEY}` } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const data = availRes.data;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!data || !data[infoHash] || !data[infoHash].rd || data[infoHash].rd.length === 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return null; // Not cached
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // B. Add Magnet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const addRes = await axios.post("https://api.real-debrid.com/rest/1.0/torrents/addMagnet", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            `magnet=${encodeURIComponent(magnet)}`, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { headers: { Authorization: `Bearer ${RD_API_KEY}` } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const torrentId = addRes.data.id;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // C. Select Files (All)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await axios.post(`https://api.real-debrid.com/rest/1.0/torrents/selectFiles/${torrentId}`, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "files=all", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { headers: { Authorization: `Bearer ${RD_API_KEY}` } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // D. Get Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const infoRes = await axios.get(`https://api.real-debrid.com/rest/1.0/torrents/info/${torrentId}`, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { headers: { Authorization: `Bearer ${RD_API_KEY}` } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Get the biggest file link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const link = infoRes.data.links[0]; 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // E. Unrestrict
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const unrestrictRes = await axios.post("https://api.real-debrid.com/rest/1.0/unrestrict/link", 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `link=${link}`, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { headers: { Authorization: `Bearer ${RD_API_KEY}` } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return unrestrictRes.data.download;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log("RD Error:", e.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // --- HANDLERS ---

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Handle Search
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    builder.defineCatalogHandler(async ({ type, id, extra }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (extra && extra.search) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const results = await searchSukebei(extra.search);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return { metas: results };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return { metas: [] };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Handle Stream Request
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                builder.defineStreamHandler(async ({ type, id }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!id.startsWith("sukebei:")) return { streams: [] };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const sukebeiId = id.split(":")[1];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const magnet = await getMagnetFromId(sukebeiId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!magnet) return { streams: [] };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Check RD
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const cachedLink = await resolveRD(magnet);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (cachedLink) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                streams: [{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name: "⚡ RD [Cached]",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                title: "Instant Stream",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                url: cachedLink
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Fallback to P2P if not cached (optional)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    streams: [{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    name: "Sukebei [P2P]",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: "Not Cached - Torrent",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    infoHash: magnet.match(/xt=urn:btih:([a-zA-Z0-9]+)/)[1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            module.exports = builder.getInterface();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            