// ... (The code for searchSukebei, resolveRD, catalogHandler remains the same)

// *************** THE CLEAN META HANDLER *****************
builder.defineMetaHandler(async ({ id }) => {
    // Decode the title without the debug lines
        const parts = id.split('|');
            const title = parts[1] ? decodeURIComponent(parts[1]) : "Sukebei Content";

                return {
                        meta: {
                                    id: id,
                                                type: "other",
                                                            name: title,
                                                                        poster: "https://via.placeholder.com/300?text=Sukebei",
                                                                                    description: "Click the button below to stream."
                                                                                            }
                                                                                                };
                                                                                                });
                                                                                                // **********************************************************

                                                                                                // *************** THE ROBUST STREAM HANDLER *****************
                                                                                                builder.defineStreamHandler(async ({ id }) => {
                                                                                                    try {
                                                                                                            if (!id.startsWith("sukebei:")) return { streams: [] };

                                                                                                                    const cleanId = id.split(":")[1];
                                                                                                                            const infoHash = cleanId.split("|")[0];

                                                                                                                                    if (!infoHash || infoHash.length < 30) return { streams: [] }; 

                                                                                                                                            const streams = [];

                                                                                                                                                    // 1. GUARANTEED P2P FALLBACK (Added first to ensure streams list is never empty)
                                                                                                                                                            streams.push({
                                                                                                                                                                        name: "Sukebei [Torrent]",
                                                                                                                                                                                    title: "Requires Client / Uncached",
                                                                                                                                                                                                infoHash: infoHash,
                                                                                                                                                                                                            sources: [`magnet:?xt=urn:btih:${infoHash}`]
                                                                                                                                                                                                                    });
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                    // 2. Try Real-Debrid (This is optional and won't block the P2P stream)
                                                                                                                                                                                                                                            const rdLink = await resolveRD(infoHash);
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            if (rdLink) {
                                                                                                                                                                                                                                                                        streams.unshift({ // use unshift to put the RD stream at the top of the list
                                                                                                                                                                                                                                                                                        name: "⚡ RD+ [Cached]",
                                                                                                                                                                                                                                                                                                        title: "Instant Stream",
                                                                                                                                                                                                                                                                                                                        url: rdLink
                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                    return { streams: streams };

                                                                                                                                                                                                                                                                                                                                                        } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                // If anything fails, return a graceful error stream
                                                                                                                                                                                                                                                                                                                                                                        return {
                                                                                                                                                                                                                                                                                                                                                                                    streams: [{
                                                                                                                                                                                                                                                                                                                                                                                                    name: "Addon Error",
                                                                                                                                                                                                                                                                                                                                                                                                                    title: `Fatal Error. Try clearing cache.`,
                                                                                                                                                                                                                                                                                                                                                                                                                                    url: "stremio:///search"
                                                                                                                                                                                                                                                                                                                                                                                                                                                }]
                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                            // ... (module.exports remains the same)
                                                                                                                                                                                                                                                                                                                                                                                                                                                            